--- 
abstract: Extremely light-weight web-based authentication manager
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  File::Copy: 0
  File::Remove: 0.37
  Test::LongString: 0.11
  Test::More: 0.42
  Test::Script: 1.02
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: TinyAuth
no_index: 
  directory: 
    - inc
    - t
requires: 
  Authen::Htpasswd: 0.15
  CGI: 3.00
  CGI::Cookie: 0
  Carp: 0
  Email::Send: 2.182
  Email::Stuff: 2.05
  File::Spec: 0.80
  FindBin: 0
  Module::CGI::Install: 0.04
  Scalar::Util: 1.15
  String::MkPasswd: 0.02
  YAML::Tiny: 1.12
  perl: 5.005
version: 0.93
